name: Sweet Sense
favicon: null
layout_spectrum: 0.33218183903954923
typography_spectrum: 0.7969896793365479
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.34125718427821994
  lightness: 0.8388580763712525
  saturation: 0.43644576449878514
  rhythmicContrast: 0.15371780539862812
purpose: []
