name: Sweet Sense
favicon: null
layout_spectrum: 0.85596
typography_spectrum: 0.7969896793365479
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#915b35'
    - '#b28962'
    - '#c5b6a4'
    - '#eee5d5'
  brandStrength: 0.6875
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
